config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "static_pages#index"

  namespace :api do
    namespace :v1 do
      resources :games
      resources :users
    end
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :game

  has_many :board_states
  TILES = 100

  def build_board
    number_of_players = 5
    player = []
    number_of_players.times do |p|
      own_tiles = []
      (TILES / number_of_players).times do |t|
        own_tiles << p
      end
      player << own_tiles
    end

    tiles = []
    10.times do |i|
      column = []
      10.times do |j|
        found = player[rand(number_of_players)].pop
        while true
          if found
            column << found
            break
          end
          found = player[rand(number_of_players)].pop
        end
      end
      tiles << column
    end

    update_attributes!({state: tiles.to_json})
  end

  after_commit :store_state
  def store_state
    board_states.create(state: self.state) if self.state
  end


end

app/models/board_state.rb
class BoardState < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
end

app/models/chat_history.rb
class ChatHistory < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  def to_json
    {
      user: self.user.email,
      message: self.message,
      created_at: self.created_at
    }.to_json
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_one :board

  has_and_belongs_to_many :users

  belongs_to :owner, class_name: "::User"

  def start!
    board = Board.create({game: self})
    board.build_board
  end

end

app/models/games_users.rb
class GamesUsers < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :games

  def join(game)
    games << game
  end

  def leave(game)
    games.delete(game)
  end

  def in_game?(game)
    games.include? game
  end

  def is_owner?(game)
    game.owner == self
  end

end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < ApplicationController
      skip_before_filter :verify_authenticity_token

      def index
        render json: Game.all, include: [:owner, :users]
      end

      def show
        render json: Game.find(params[:id])
      end

      def create
        game = Game.new(name: params[:name], owner: current_user)
        if game.save
          current_user.join(game)
          render json: game, include: [:owner, :users]
        else
          render json: { errors: game.errors.full_messages }, status: 500
        end
      end

      def destroy
        Game.find(params[:id]).destroy
        render nothing: true
      end

    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      skip_before_filter :verify_authenticity_token

      def index
        render json: User.all
      end

      def show
        render json: User.find(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all || []
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    game.owner = current_user
    if game.save
      current_user.join(game)
      flash[:notice] = "New game created."
      redirect_to action: :index
    else
      flash[:error] = "Could not create new game."
      redirect_to action: :index
    end
  end

  def show
    @game = Game.find(params[:id])
    @history = ChatHistory.where(game: @game).includes(:user).limit(10).order("id DESC").reverse
  end

  def join
    game = Game.find(params[:game_id])
    current_user.join(game)
    redirect_to action: :index
  end

  def leave
    game = Game.find(params[:game_id])
    current_user.leave(game)
    redirect_to action: :index
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy!
    redirect_to action: :index
  end

  private

    def game_params
      params.require(:game).permit(:name)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ng_controller_name
    self.controller.class.name.gsub!("Controller", "Ctrl")
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/games/index.html.erb
<h2>Available Games <small>Global War</small></h2>

<div>
  <label>Name:</label>
  <input type="text" ng-model="name" placeholder="Enter a name here">
  <hr>
  <h1>Hello {{name}}!</h1>
</div>

<% unless @games.empty? %>
  <h3>Games</h3>
  <% @games.each do |game| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>
          <%= game.name %>
          <small>by: <%= game.owner.email %></small>
          <div class="pull-right">
            <% if current_user.in_game? game %>
              <%= link_to 'Enter Game', game_path(game), class: 'btn btn-success btn-sm' %>
              <%= link_to "Leave", game_leave_path(game), method: :post, class: 'btn btn-primary btn-sm' %>
            <% else %>
              <%= link_to "Join", game_join_path(game), method: :post, class: 'btn btn-primary btn-sm' %>
            <% end %>
            <% if current_user.is_owner? game %>
              <%= link_to 'Delete Game', game, method: :delete, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
        </h4>
      </div>
      <div class="panel-body">
        <div class="row-fluid">
          <strong>Players</strong>
          <ol>
            <% game.users.each do |user| %>
               <li><%= user.email %></li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<hr>

<h4>Create new game</h4>
<%= bootstrap_form_for(@game, layout: :inline) do |f| %>
  <%= f.text_field :name, hide_label: true %>
  <%= f.primary %>
<% end %>

<hr>

app/views/games/show.html.erb
<%= link_to 'Back', games_path %>



<table class="table" style="min-height: 500px; min-width: 500px">
  <% JSON.parse(@game.board.state).each do |row| %>
    <tr>
      <% row.each do |cell| %>
        <% colors = ['#FBB735', '#EB403B', '#39C0B3', '#274389', '#227FB0' ] %>
        <td style="background-color: <%= colors[cell] %>"></td>
      <% end %>
    </tr>
  <% end %>
</table>

<div class="row">
  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>
          <%= @game.name %>
          <small>by: <%= @game.owner.email %></small>
        </h4>
      </div>
      <div class="panel-body">
        <div class="row-fluid">
          <strong>Players</strong>
          <ol>
            <% @game.users.each do |user| %>
               <li><%= user.email %></li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-9">
    <div class='panel panel-default'>
      <div class='panel-heading'>Discussion</div>
      <div id="chat-container" style="overflow-y: scroll; height:200px;">
        <table class="table" id="chat">

        <% @history.each do |h| %>
          <tr><td><%= h.user.email %></td><td><%= h.message %></td><td><%= h.created_at %></td></tr>
        <% end %>
        </table>
      </div>
      <form id="input-form" style="background: #999; padding: 7px 5px">
        <div class="row-fluid">
          <div class="input-group">
            <input id="input-text" type="text" class="form-control col-lg-10" placeholder="Enter chat text here!" autocomplete="off" autofocus />
            <span class="btn btn-primary input-group-addon" type="submit">Send</span>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  var scheme   = "ws://";
  var uri      = scheme + window.document.location.host + "/";
  var ws       = new WebSocket(uri);

  // public/assets/js/application.js
  ws.onmessage = function(message) {
    var data = JSON.parse(message.data);
    $("#chat").append("<tr><td>" + data.user + "</td><td>" + data.message + "</td><td>" + data.created_at + "</td></tr>")
    $("#chat-container").stop().animate({
      scrollTop: $('#chat').height()
    }, 500);
  };

  // public/assets/js/application.js
  $("#input-form").on("submit", function(event) {
    event.preventDefault();
    var text   = $("#input-text")[0].value;
    ws.send(JSON.stringify({ game_id : <%= params[:id] %>, text: text }));
    $("#input-text")[0].value = "";
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="globalWarApp">
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <div ng-view></div>
  </div>
</body>
</html>